server:
  port: 7900
  tomcat:
    basedir: /home/temp

spring:
  application:
    name: common-server-v1

  profiles:
    active: local

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#配置断路由的超时时间
hystrix:
  command:
    defalut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

td:
  swagger:
    enable: true

log:
  file-name: /home/that-day/logs/${spring.application.name}
