server:
  port: 7900
  tomcat:
    basedir: /home/temp

nacos-addr: 127.0.0.1:8848

spring:
  application:
    name: common-server-v1

  profiles:
    active: local

  cloud:
    nacos:
      discovery:
        server-addr: ${nacos-addr}

#配置Dubbo
dubbo:
  application:
    name: dubbo-${spring.application.name}
  registry:
    id: dubbo-${spring.application.name}
    timeout: 5000
    address: ${nacos-addr}
    protocol: nacos
  consumer:
    timeout: 5000
  provider:
    timeout: 5000

td:
  swagger:
    enable: true
