server:
  port: 7901
  tomcat:
    basedir: /home/temp

nacos-config:
  addr: 127.0.0.1:8848
  user: nacos
  psw: nacos

spring:
  application:
    name: common-server-v1

  profiles:
    active: local

  cloud:
    nacos:
      #discovery与config的server-addr没配置默认是读取这个的
      server-addr: ${nacos-config.addr}

#配置Dubbo
dubbo:
  application:
    name: dubbo-${spring.application.name}
  registry:
    id: dubbo-${spring.application.name}
    timeout: 5000
    address: ${nacos-config.addr}
    protocol: nacos
  consumer:
    timeout: 5000
    check: false
  provider:
    timeout: 5000
    protocol: dubbo

td:
  swagger:
    enable: true
