server:
  port: 7200

spring:
  application:
    name: common-server-v1

  profiles:
    active: local

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

datasource:
  tinyid:
    names: m
  tinyid.m:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/that_day?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root

batch:
  size:
    max: 100000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

#log
logging:
  config: classpath:logback-admin.xml
log:
  file: /home/that-day/logs/${spring.application.name}

swagger:
  enable: true