server:
  port: 8000

spring:
  application:
    name: server-gateway1

  main:
    allow-bean-definition-overriding: true

  profiles:
    active: local

  #网关配置了 微服务也要配置的
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  #  redis:
  #    host: 127.0.0.1
  #    port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        heart-beat-timeout: 6
        ip-delete-timeout: 9

    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/globalFallback
      routes:
        #用户服务
        - id: user-v1
          uri: lb://user-v1
          predicates:
            - Path=/v1/user-api/**
          filters:
            - StripPrefix=2
        #socket服务
        #        - id: socket
        #          uri: lb:ws://user-v1
        #          predicates:
        #            - Path=/v1/user-ss/**
        #          filters:
        #            - StripPrefix=2
        #id服务
        - id: common-server-v1
          uri: lb://common-server-v1
          predicates:
            - Path=/v1/common-api/**
          filters:
            - StripPrefix=2
        - id: rouyi-v1
          uri: lb://rouyi-v1
          predicates:
            - Path=/v1/rouyi/**
          filters:
            - StripPrefix=2

#配置断路由的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

#log
logging:
  config: classpath:logback-admin.xml
log:
  file: /home/that-day/logs/${spring.application.name}
