server:
  port: 8000

nacos-config:
  addr: 127.0.0.1:8848
  user: nacos
  psw: nacos

spring:
  application:
    name: server-gateway-a
  main:
    allow-bean-definition-overriding: true

  #上传那文件大小 网关配置了 微服务也要配置的
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  #redis配置
#  redis:
#      host: 127.0.0.1
#      port: 6379

  cloud:
    #限流 nacos配置
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        gw-flow:
          nacos:
            username: ${nacos-config.user}
            password: ${nacos-config.psw}
            server-addr: ${nacos-config.addr}
            dataId: ${spring.application.name}-gateway-flow
            groupId: SENTINEL_GROUP
            rule-type: gw-flow
        gw-api-group:
          nacos:
            username: ${nacos-config.user}
            password: ${nacos-config.psw}
            server-addr: ${nacos-config.addr}
            dataId: ${spring.application.name}-gateway-api
            groupId: SENTINEL_GROUP
            rule-type: gw-api-group
    #网关配置
    gateway:
      #跨域配置 网关配置了微服务就不需要配置了 否则不生效的
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      #熔断配置
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/globalFallback
      #路由配置
      routes:
        #socket服务
        - id: socket
          uri: lb:ws://api-v1
          predicates:
            - Path=/v1/api-ws/**
          filters:
            - StripPrefix=2
        #api服务
        - id: es-v1
          uri: lb://es-v1
          predicates:
            - Path=/v1/es/**
          filters:
            - StripPrefix=2
        - id: api-v1
          uri: lb://api-v1
          predicates:
            - Path=/v1/api/**
          filters:
            - StripPrefix=2
        - id: common-server-v1
          uri: lb://common-server-v1
          predicates:
            - Path=/v1/common/**
          filters:
            - StripPrefix=2
        - id: mm-admin-v1
          uri: lb://mm-admin-v1
          predicates:
            - Path=/v1/admin/**
          filters:
            - StripPrefix=2

#配置断路由的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          #请求的最大数目默认是10 超过这个会抛异常
          semaphore:
            maxConcurrentRequests: 1000
          thread:
            timeoutInMilliseconds: 16000

td:
  swagger:
    enable: true
