server:
  port: 8000

spring:
  application:
    name: server-gateway1

  main:
    allow-bean-definition-overriding: true

  profiles:
    active: local

  #网关配置了 微服务也要配置的
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  #  redis:
  #    host: 127.0.0.1
  #    port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      default-filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/globalFallback
      routes:
        #api服务
        - id: api-v1
          uri: lb://api-v1
          predicates:
            - Path=/v1/api/**
          filters:
            - StripPrefix=2
        #socket服务
        #        - id: socket
        #          uri: lb:ws://user-v1
        #          predicates:
        #            - Path=/v1/user-ss/**
        #          filters:
        #            - StripPrefix=2
        #id服务
        - id: common-server-v1
          uri: lb://common-server-v1
          predicates:
            - Path=/v1/common/**
          filters:
            - StripPrefix=2
        - id: mm-admin-v1
          uri: lb://mm-admin-v1
          predicates:
            - Path=/v1/admin/**
          filters:
            - StripPrefix=2

#配置断路由的超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

#log
logging:
  config: classpath:logback-admin.xml

td:
  swagger:
    enable: true
  log:
    fileName: /home/that-day/logs/${spring.application.name}
