server:
  port: 7210
  tomcat:
    basedir: /home/temp

spring:
  application:
    name: api-v1
  profiles:
    active: local

  #  redis:
  #    host: 127.0.0.1
  #    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        flow:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow
        degrade:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
        system:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
        authority:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
        param-flow:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow

#配置断路由的超时时间
hystrix:
  command:
    defalut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000



td:
  swagger:
    enable: true

log:
  file-name: /home/that-day/logs/${spring.application.name}

wx:
  #小程序
  miniapp:
    configs:
      - appid: wx000000000000
        secret: 0000000000000000000
  #公众号
  mp:
    configs:
      - appid: wx111111111110
        secret: 111111111111111111111111111
