server:
  port: 7100

spring:
  application:
    name: user-v1
  profiles:
    active: local

  #  redis:
  #    host: 127.0.0.1
  #    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

#log
logging:
  config: classpath:logback-admin.xml
log:
  file: /home/that-day/logs/${spring.application.name}

swagger:
  enable: false