server:
  port: 7200
  tomcat:
    basedir: /home/temp

spring:
  application:
    name: user-v1
  profiles:
    active: local

  #  redis:
  #    host: 127.0.0.1
  #    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    sentinel:
      transport:
        dashboard: localhost:8080

#配置断路由的超时时间
hystrix:
  command:
    defalut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#log
logging:
  config: classpath:logback-admin.xml


td:
  swagger:
    enable: true
  log:
    fileName: /home/that-day/logs/${spring.application.name}
