server:
  port: 7210
  tomcat:
    basedir: /home/temp

nacos-config:
  addr: 127.0.0.1:8848
  user: nacos
  psw: nacos

spring:
  application:
    name: api-v1
  profiles:
    active: local

  #  redis:
  #    host: 127.0.0.1
  #    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    hibernate:
      ddl-auto: none

  cloud:
    nacos:
      #discovery与config的server-addr没配置默认是读取这个的
      server-addr: ${nacos-config.addr}

    sentinel:
      transport:
        dashboard: localhost:8080
      datasource:
        flow:
          nacos:
            username: ${nacos-config.user}
            password: ${nacos-config.psw}
            server-addr: ${nacos-config.addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            # 规则类型，取值见：
            # org.springframework.cloud.alibaba.sentinel.datasource.RuleType
            rule-type: flow
        degrade:
          nacos:
            username: ${nacos-config.user}
            password: ${nacos-config.psw}
            server-addr: ${nacos-config.addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
        system:
          nacos:
            username: ${nacos-config.user}
            password: ${nacos-config.psw}
            server-addr: ${nacos-config.addr}
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            rule-type: system
        authority:
          nacos:
            username: ${nacos-config.user}
            password: ${nacos-config.psw}
            server-addr: ${nacos-config.addr}
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            rule-type: authority
        param-flow:
          nacos:
            username: ${nacos-config.user}
            password: ${nacos-config.psw}
            server-addr: ${nacos-config.addr}
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: param-flow

#配置Dubbo
dubbo:
  application:
    name: dubbo-${spring.application.name}
  registry:
    id: dubbo-${spring.application.name}
    timeout: 5000
    address: ${nacos-config.addr}
    protocol: nacos
  consumer:
    timeout: 5000
    #启动不检查服务提供者,检查不到提供者,则启动不了项目
    check: false
    #负载均衡 默认是random随机的 现在这个是轮询
    loadbalance: roundrobin
  provider:
    timeout: 5000
    protocol: dubbo

#分布式事务
seata:
  tx-service-group: admin-tx-group
  service:
    vgroup-mapping:
      admin-tx-group: default  #key与上面的tx-service-group的值对应并与config的一致
  config:
    type: nacos
    nacos:
      namespace: seata
      server-addr: ${nacos-config.addr}
      username: ${nacos-config.user}
      password: ${nacos-config.psw}
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${nacos-config.addr}
      username: ${nacos-config.user}
      password: ${nacos-config.psw}

td:
  swagger:
    enable: true

wx:
  #小程序
  miniapp:
    configs:
      - appid: wx000000000000
        secret: 0000000000000000000
  #公众号
  mp:
    configs:
      - appid: wx111111111110
        secret: 111111111111111111111111111

