#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://192.168.224.129:3306/that_day?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: root

  redis:
    #数据库索引
    database: 0
    #host: 192.168.224.129
    #port: 6379
    password: ""
    #连接超时时间
    timeout: 5000
    cluster:
      nodes:
        - 192.168.224.129:7001
        - 192.168.224.129:7002
        - 192.168.224.129:7003

#是否允许生成代码，生产环境设置为false
generator:
  enabled: true


# IP 本地解析
ip:
  local-parsing: true


